repos:
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    - id: black
-   repo: git://github.com/pycqa/flake8
    rev: 3.8.2
    hooks:
    -   id: flake8
-   repo: git://github.com/timothycrosley/isort 
    rev: 5.3.0
    hooks:
    - id: isort
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
